server:
  port: 8080

spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/auto_catalog
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update